### ISSUE TITLE
NoneType exception in 1.5.0

### ISSUE THREAD

**Issue by mafrosis** [s3tools/s3cmd#474]
Updated from pypi today, trying to get `s3cmd` working with an existing 1.3.0 install of [s3proxy](https://github.com/andrewgaul/s3proxy).

	vagrant@hostname:/srv> s3cmd la                                                  

	Invoked as: /usr/local/bin/s3cmd la
	Problem: AttributeError: 'NoneType' object has no attribute 'getchildren'
	S3cmd:   1.5.0
	python:   2.7.3 (default, Mar 13 2014, 11:03:55)
	[GCC 4.7.2]
	environment LANG=en_AU.UTF-8

	Traceback (most recent call last):
	  File "/usr/local/bin/s3cmd", line 2543, in <module>
	    rc = main()
	  File "/usr/local/bin/s3cmd", line 2456, in main
	    rc = cmd_func(args)
	  File "/usr/local/bin/s3cmd", line 146, in cmd_all_buckets_list_all_content
	    subcmd_bucket_list(s3, S3Uri("s3://" + bucket["Name"]))
	  File "/usr/local/bin/s3cmd", line 158, in subcmd_bucket_list
	    response = s3.bucket_list(bucket, prefix = prefix)
	  File "/usr/local/lib/python2.7/dist-packages/S3/S3.py", line 285, in bucket_list
	    response = self.bucket_list_noparse(bucket, prefix, recursive, uri_params)
	  File "/usr/local/lib/python2.7/dist-packages/S3/S3.py", line 309, in bucket_list_noparse
	    response = self.send_request(request)
	  File "/usr/local/lib/python2.7/dist-packages/S3/S3.py", line 1032, in send_request
	    e = S3Error(response)
	  File "/usr/local/lib/python2.7/dist-packages/S3/Exceptions.py", line 62, in __init__
	    self.info.update(self.parse_error_xml(tree))
	  File "/usr/local/lib/python2.7/dist-packages/S3/Exceptions.py", line 101, in parse_error_xml
	    for child in error_node.getchildren():
	AttributeError: 'NoneType' object has no attribute 'getchildren'

My configuation file has the following changes, as per the [compat wiki](https://github.com/andrewgaul/s3proxy/wiki/S3Proxy-compatibility-list) on `s3proxy`:

    [default]
    access_key = local-identity
    secret_key = local-credential
    host_base = localhost:8880
    host_bucket = localhost:8880

**Comment by mdomsch** [comment]
We failed to parse a response that probably came from s3proxy. What does
running with --debug show?

**Comment by mdomsch** [comment]
I bet it does not like signature v4.  Try --signature-v2.

**Comment by mdomsch** [comment]
or SSL.

You might also try with the one additional patch I've pushed here:
https://github.com/mdomsch/s3cmd/tree/bug/proxy-exceptions
to debug the error document returned from the proxy.

Thanks,
Matt

**Comment by mafrosis** [comment]
Hey thanks for getting back to me.  The `--debug` flag uncovered a little bit of weirdness - the request to `la` is finding buckets with underscores in the name; which is an illegal char and causes the later exception.

For whatever reason, the first request to `s3proxy` returns the list of directories in `/tmp` as my buckets - including an invalid bucket called "host_machine". The subsequent request for `/host_machine/?delimiter=/` to `s3proxy` then results in a `java.lang.NullPointerException` in `s3proxy`. 

Here's a gist with the entirety of the debug output so you can fix the exception handling in `s3cmd`, if you like:
https://gist.github.com/mafrosis/d384dc0a8fe1c630870d

**Comment by mdomsch** [comment]
would you mind pulling my bug/proxy-exceptions tree again and trying?  I'd
love to see if this succeeds in reporting the error as returned.  Thanks
for the gist - that was really helpful.
-Matt

**Comment by andrewgaul** [comment]
The logs contain:

```
DEBUG: Unicodising "Bucket name 'host_machine' contains disallowed character '_'. The only supported ones are: lowercase us-ascii letters (a-z), digits (0-9), dot (.) and hyphen (-)." using UTF-8
```

While [Amazon documents](http://docs.amazonwebservices.com/AmazonS3/2006-03-01/dev/index.html?BucketRestrictions.html) this restriction, it does not actually enforce it for bucket-in-path names and for other S3 clones with looser naming restrictions.

**Comment by mafrosis** [comment]
@mdomsch Here's another gist containing the output from `s3cmd la` on mdomsch/s3cmd@41f4f68

https://gist.github.com/mafrosis/fa7eab019e177f62eff0

**Comment by andrewgaul** [comment]
@mafrosis The `NullPointerException` looks more like an S3Proxy issue.  Does the S3Proxy console emit a more informative stack trace?  Also can try re-running s3proxy with debug logging via:

```
java -DLOG_LEVEL=trace -jar s3proxy
```

**Comment by mdomsch** [comment]
Thanks.  Given that this patch works as I expected in your failure case,
I've pulled it onto the master branch now.

**Comment by mafrosis** [comment]
@andrewgaul The `NullPointerException` is certainly an S3Proxy issue. I'll continue with this over on andrewgaul/s3proxy#39
